### ISSUE TITLE
Installed assertive.types manually, but when installing Rnssp, vignette build failed

### ISSUE THREAD

**Issue by ajstamm** [CDCgov/Rnssp#15]
I was able to download and install assertive.base, assertive.properties, and assertive.types from CRAN archives and install them manually. I also had to install ggside separately. When I tried to install Rnssp after that, I was able to install it without vignettes, but not with vignettes. When I tried to install with vignettes, I got the following error. 

```r
> devtools::install_github("cdcgov/Rnssp", build_vignette = TRUE)
Downloading GitHub repo cdcgov/Rnssp@HEAD
Skipping 1 packages not available: assertive.types
── R CMD build ───────────────────────────────────────────────────────────────────────────
✔  checking for file 'C:\Users\ajstamm\AppData\Local\Temp\RtmpkfB0xK\remotes4bbc78167a45\CDCgov-Rnssp-afbcb80/DESCRIPTION' ...
─  preparing 'Rnssp': (533ms)
✔  checking DESCRIPTION meta-information ... 
─  installing the package to build vignettes
E  creating vignettes (12.9s)
   --- re-building 'Rnssp_intro.Rmd' using rmarkdown
   
   Quitting from lines 54-55 [load] (Rnssp_intro.Rmd)
   Error: processing vignette 'Rnssp_intro.Rmd' failed with diagnostics:
   cannot open the connection
   --- failed re-building 'Rnssp_intro.Rmd'
   
   --- re-building 'Rnssp_rstudio_addins.Rmd' using rmarkdown
   --- finished re-building 'Rnssp_rstudio_addins.Rmd'
   
   --- re-building 'Rnssp_text_mining.Rmd' using rmarkdown
   
   Quitting from lines 51-52 [load] (Rnssp_text_mining.Rmd)
   Error: processing vignette 'Rnssp_text_mining.Rmd' failed with diagnostics:
   cannot open the connection
   --- failed re-building 'Rnssp_text_mining.Rmd'
   
   --- re-building 'Rnssp_trend_alert_detection.Rmd' using rmarkdown
   
   Quitting from lines 43-45 [load] (Rnssp_trend_alert_detection.Rmd)
   Error: processing vignette 'Rnssp_trend_alert_detection.Rmd' failed with diagnostics:
   cannot open the connection
   --- failed re-building 'Rnssp_trend_alert_detection.Rmd'
   
   SUMMARY: processing the following files failed:
     'Rnssp_intro.Rmd' 'Rnssp_text_mining.Rmd'
     'Rnssp_trend_alert_detection.Rmd'
   
   Error: Vignette re-building failed.
   Execution halted
Error: Failed to install 'Rnssp' from GitHub:
  ! System command 'Rcmd.exe' failed
```

**Comment by rosericazondekon** [comment]
Dear @ajstamm 

Thank you for opening this issue. It is understandable that installing Rnssp with vignettes will fail as they require user's credentials to build successfully. Therefore, vignettes' builds can not be completed during package installation. 

Please proceed to its installation without building the vignettes. 

Renders of the Rnssp vignettes are available on the [Rnssp online documentation](https://cdcgov.github.io/Rnssp/articles).

**Comment by rosericazondekon** [comment]
Dear @ajstamm ,

We just released `Rnssp v0.3.0` which among other features, updates, and , resolves the `assertive.types` dependency issue. 

Please, feel free to check the new release note for an exhaustive list of the novelties.

You may install the newly released version by running:
```
devtools::install_github("cdcgov/Rnssp")
```

If you still want to build `Rnssp` with vignettes, here is how to do it with this version:

* Create an  NSSP user profile and call it `myProfile`. You can do it with the `create_profile()` function of the `Rnssp` package (`myProfile <- create_profile()`). Then enter your BioSense credentials.
* Save the `myProfile` object to your home directory as an `.rds` file (`saveRDS(myProfile, "~/myProfile.rds")`) and as an `.rda` file (`save(myProfile, file = "~/myProfile.rda)`).
* Finally, build the package with vignettes.

Thank you for your interest in this project, and for your contribution.

**Comment by ajstamm** [comment]
I was able to install the package and create a profile, but I still can't install vignettes. My error:

`> devtools::install_github("cdcgov/Rnssp", build_vignettes = TRUE)`
Downloading GitHub repo cdcgov/Rnssp@HEAD
── R CMD build ────────────────────────────────────────────────────────────
✔  checking for file 'C:\Users\stamma1\AppData\Local\Temp\Rtmp6tIN7l\remotes23b45d0f729\CDCgov-Rnssp-f09bedb/DESCRIPTION' (341ms)
─  preparing 'Rnssp': (659ms)
✔  checking DESCRIPTION meta-information ...
─  installing the package to build vignettes
E  creating vignettes (23.9s)
   --- re-building 'Rnssp_intro.Rmd' using rmarkdown
   --- finished re-building 'Rnssp_intro.Rmd'
   
   --- re-building 'Rnssp_rstudio_addins.Rmd' using rmarkdown
   --- finished re-building 'Rnssp_rstudio_addins.Rmd'
   
   --- re-building 'Rnssp_text_mining.Rmd' using rmarkdown
   --- finished re-building 'Rnssp_text_mining.Rmd'
   
   --- re-building 'Rnssp_trend_alert_detection.Rmd' using rmarkdown
   
   Quitting from lines 73-76 [hhs] (Rnssp_trend_alert_detection.Rmd)
   Error: processing vignette 'Rnssp_trend_alert_detection.Rmd' failed with diagnostics:
   no applicable method for 'group_by' applied to an object of class "list"
   --- failed re-building 'Rnssp_trend_alert_detection.Rmd'
   
   SUMMARY: processing the following file failed:
     'Rnssp_trend_alert_detection.Rmd'
   
   Error: Vignette re-building failed.
   Execution halted
Error: Failed to install 'Rnssp' from GitHub:
  ! System command 'Rcmd.exe' failed

**Comment by rosericazondekon** [comment]
Hi @ajstamm ,

Looking at your log, I can see that the `Rnssp_intro.Rmd` and the `Rnssp_text_mining.Rmd` vignettes build successfully. Have you also saved your `myProfile` object in your home folder as `myProfile.rda`? If not, do it with `save(myProfile, file = "~/myProfile.rda")` and try it again. You will need to have both the `myProfile.rds` and `myProfile.rda`  files saved in your home directory to successfully build `Rnssp` with vignettes.

Please, let me know how it goes.

Best,
